### ISSUE TITLE
Access by Reflection from outside

### ISSUE THREAD

**Issue by PinkaminaDianePie** [wycats/javascript-private-state#9]
> - Not accessible via external reflection API

why? as for me its the worst part of spec. its not rare case if i found a library which fit most of my requirements, but something is broken/buggy, and fastest way to force this work is monkey-patching. how do i handle it if language will have something `private`? its not a big problem for some other languages like java or c++, where we have huge standard libs or external frameworks like qt or boost. in javascript we have nothing out of box and forced to use a lot of external libs, with some problems with part of them. so monkey-patching is the very usefull feature.

**Comment by ljharb** [comment]
How do you handle it now if I hide aspects of my program via a closure? For example:

``` js
var myExportedThing = (function () {
  var privateThing = {};
  return {
    get: function (key) { return privateThing['$' + key]; },
    set: function (key, value) { privateThing['$' + key] = value; }
  };
}());
```

**Comment by PinkaminaDianePie** [comment]
@ljharb its only one part of language (and probably not the best), but now you want to add one another. we have `Reflect`, why not to use it? adding `private` without reflection will add more problems to language, than benefits.
